version: '3.4'

services:
  calculator:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1020:4000"
    env_file:
      - .env-docker/.env-calculator


  db:
    image: postgres
    ports:
      - localhost:5433:5432
    env_file:
      - .env-docker/.env-db
    volumes:
      - ./volumes/db:/var/lib/postgresql

