version: '3.4'

services:
  calculator:
    image: econgood/balance-sheet-api:latest
    depends_on:
      - db
    ports:
      - "1020:4000"
    env_file:
      - .env-docker/.env-calculator
    volumes:
      - ./volumes/logs:/home/node/app/logs


  db:
    image: postgres
    env_file:
      - .env-docker/.env-db
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

