name: Build docker image
on:
  push:
    branches: ['main']
  pull_request:
    branches: [ 'main' ]
env:
  NODE_VERSION: 18.7.0

jobs:
  checks:
    uses: ./.github/workflows/check-workflow.yml
    with:
      node-version: 18.7.0
    secrets: inherit
